[ERROR] 2019-12-12 13:33:20,907 django.request: Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\admin\sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\admin\sites.py", line 212, in inner
    if not self.has_permission(request):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\admin\sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\utils\functional.py", line 256, in inner
    self._setup()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\utils\functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 54, in __getitem__
    return self._session[key]
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 402, in get
    num = len(clone)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 256, in __len__
    self._fetch_all()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
[ERROR] 2019-12-12 13:33:51,546 django.request: Internal Server Error: /admin/log_viewer/
Traceback (most recent call last):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\decorators.py", line 44, in <lambda>
    lambda u: u.is_authenticated,
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\utils\functional.py", line 256, in inner
    self._setup()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\utils\functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\auth\__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 54, in __getitem__
    return self._session[key]
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 402, in get
    num = len(clone)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 256, in __len__
    self._fetch_all()
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\manish.singh\PycharmProjects\Django-Tutorial\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
